### ISSUE TITLE
Update for JDA4.

### ISSUE THREAD

**Issue by rainestormee** [Comportment/JDA-Command#15]
Let’s make sure that everything will still be compatible with the new JDA when that is released.

**Comment by Andre601** [comment]
Is there already a dev-build available to test and use with JDA 4?
I want to try the V4 but I can't without updating this library

**Comment by rainestormee** [comment]
Honestly I don't think JDA-4 makes any breaking changes to this code - I will look into it however. This was designed very abstractly SO this shouldn't affect it as well.

**Comment by Andre601** [comment]
Yeah. I just found out that I can just use the commit has as version thanks to jitpack.
However, Another dependency I have isn't updated for JDA 4, so I can't quite test it yet....

**Comment by rainestormee** [comment]
Fixed this by adding in an abstraction layer using Java Generics, JDA-Command no longer cares what version of JDA you are using, or even if you are going to use it lol.
