### ISSUE TITLE
Is it possible to find which command alias was used?

### ISSUE THREAD

**Issue by Andre601** [Comportment/JDA-Command#18]
I would like to know if there would be a way to retrieve the command alias that was used to trigger the execute.

The only *solution* I could think of would be in combination with a message receive listener to check if received message equals x, which seems a bit much.
An additional (optional) argument of some sort (or something similar) would be nice as I want to customize certain commands depending on what alias was used.

I hope this makes sense.

**Comment by rainestormee** [comment]
@Andre601, try the latest release (1.1.5) - is this the feature you wanted?

**Comment by Andre601** [comment]
Perhaps. I honestly don't need it anymore at that point, but I still updated... Interestingly enough does Dependabot have issues with updating this dependency... It seems to even not be able to find it.... so stupid.

**Comment by rainestormee** [comment]
Hmm, that's strange - the latest release is on Jitpack... https://jitpack.io/#rainestormee/jda-command/1.1.5. I've been tempted to switch over to using GitHub for deploying packages. I'll try and compile a test project against this tomorrow morning / afternoon.

**Comment by rainestormee** [comment]
Jup, I managed to find the release, maybe dependabot takes a while to update?

**Comment by Andre601** [comment]
It *should* usually update on the next time it checks, but it seems to just be stupi.d
You should perhaps consider publishing it to like bintray or whatever.
